[package]
name = "rdb"
version = "0.1.0"
authors = ["jfarrell468 <jfarrell468@gmail.com>"]
edition = "2018"

[dependencies]
commitlog = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "~0.10"
sstable = "~0.6"
